spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: prod
  application:
    name: "HealthApp"
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/healthapp}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: ERROR
    —Åom.app.health: INFO

upload:
  path: src/main/resources/images
